### ISSUE TITLE
Implement license

### ISSUE THREAD

**Issue by connorhsm** [connorhsm/Flux-Project-Manager#10]
@KipCrossing are there any guidelines on this in relation to the bot being used/for Flux?
Otherwise, I usually license as GPL 3.0.

**Comment by KipCrossing** [comment]
Any reason to go with GPL instead of a permissive licence like MIT or Apache 2.0? I'd just like to know your thoughts. 

Reading the [tldr](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)), it seems fine as long as everyone uses git. Also, its the kind of a product with a specific use, and it's not like anyone else will have a use case for it; unless they modify it, say, to make a "general" project management bot. Should we let them?
- Yes - LGPL
- No - GPL

Free reign? Apache 2.0 (Which apparently has protections for coder negligence)

**Comment by connorhsm** [comment]
No reason necessarily, it often just seems the best fit for my work in most cases.
In this case, a more permissive license may be appropriate. Specifically, because it may take a significant amount of more work to modify this to be used elsewhere and given how niche this project is, that may be unlikely.

Upon further research, I propose we consider the MIT license as it is reportedly one of the most permissive, it grants no liability for any damage caused and mostly, it's short, simple and clear.

A good source https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered

**Comment by KipCrossing** [comment]
Yes, I like MIT for that reason. 

Just keep in mind the scope of the project. V1 Didn't really capture user data; just a name and that could have been a nickname. Further, the flux discord server is pretty public, but what if it were used on a private server with private/secrete information and the bot released it to the world (A data breach)? Does MIT cover us for that? Not sure... Any ambiguity will be used against the coder in Australian law; [See section 6.2](https://eprints.qut.edu.au/7404/1/open_source_book.pdf)  (in ref to GPL but still applies).

Apache 2.0 has a very robust clause for this; [See clause 8](https://www.apache.org/licenses/LICENSE-2.0.html).

Really, I'm easy. Just keep in mind scope creep for this projet; like putting phone numbers on a public spreadsheet could be not so nice.

**Comment by KipCrossing** [comment]
>  scope creep
I'm looking at you Ben

**Comment by connorhsm** [comment]
Okay, thanks for this. Apache 2.0 may be the way to go in the end then.

I'm fairly sure Ben wanted to involve phone numbers (and @voteflux.org emails already exist in this repo), which would ultimately be stored in the sheet. A note, we may need to clarify on the form how and where this information will be kept and used.

**Comment by KipCrossing** [comment]
I'll add the same to my Repo and they should merge fine.
